---

- name: PROOF OF CONCEPT Device Automation
  hosts: POCDE9K02
  gather_facts: no

  tasks:

    - name: default interfaces
      nxos_interface: interface={{ item }} state=default host={{ inventory_hostname }}
      with_items:
        - Ethernet1/53
        - Ethernet1/54
    # Ensure an interface is a Layer 3 port and that it has the proper description
    - name: config interface
      nxos_interface: interface=Ethernet1/53 description='Configured by Ansible' mode=layer3 host={{ inventory_hostname }}
                                                               
    # Admin down an interface
    - nxos_interface: interface=Ethernet1/54 admin_state=down host={{ inventory_hostname }} 
    # version 1

